### ISSUE TITLE
doc.find is not a function

### ISSUE THREAD

**Issue by WuglyakBolgoink** [apache/cordova-common#156]
# Bug Report

### What is expected to happen?

cordova prepare should be finished successful

### What does actually happen?

ios prepare finished with 
doc.find is not a function

```
doc.find is not a function
TypeError: doc.find is not a function
    at Object.resolveParent (/Users/.../.npm-global/lib/node_modules/cordova/node_modules/cordova-common/src/util/xml-helpers.js:131:51)
```

the problem is on this code block 
![image](https://user-images.githubusercontent.com/2271337/107623858-44ad5a00-6c5a-11eb-8daa-3c0c7a26a179.png)

## Information

The `/cordova_v10_staging/platforms/ios/ios.json` file contain only two permission descriptions in `config_munge.files.*-Info.plist` section:

![image](https://user-images.githubusercontent.com/2271337/107623398-8db0de80-6c59-11eb-9931-9cdd7d736962.png)

should contain all permissions

### Command or Code

I use simple bash script for cleaning, install and upgrade plugins and platforms. In this case I just use clean function

```bash
function clean_cordova_project_folder() {
    cd "$1" || exit

    echo "clean_cordova_project_folder -> $1"

   #  rm -rf node_modules
    rm -rf platforms
    rm -rf plugins
    rm -rf ul_web_hooks
    rm -rf package-lock.json

    npm install

    cordova prepare --verbose --debug

    cd ..
}


APP_FOLDER_STAGE="<yout_cordova_project_folder>" 
# 1. clean folders and install packages
clean_cordova_project_folder "$APP_FOLDER_STAGE"
```

### Environment, Platform, Device

- macos Catalina (10.15.7 (19H512))

### Version information

- cordova@10.0.0
- cordova-ios@6.2.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by raphinesse** [comment]
Thanks for your bug report. Could you please:

- provide a test case (either a minimal app or a unit test case) that triggers this behavior
- provide the stack trace for the error you describe

**Comment by WuglyakBolgoink** [comment]
@raphinesse  I try to find a 100% reproducible case...


But now only stacktrace:

```
Prepared iOS project successfully
doc.find is not a function
TypeError: doc.find is not a function
    at Object.resolveParent (/Users/xxxxx/.npm-global/lib/node_modules/cordova/node_modules/cordova-common/src/util/xml-helpers.js:132:24)
    at /Users/xxxxx/.npm-global/lib/node_modules/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:315:59
    at Array.forEach (<anonymous>)
    at PlatformMunger._is_conflicting (/Users/xxxxx/.npm-global/lib/node_modules/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:307:21)
    at PlatformMunger.add_config_changes (/Users/xxxxx/.npm-global/lib/node_modules/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:176:44)
    at /Users/xxxxx/.npm-global/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare/platforms.js:66:24
    at async Promise.all (index 0)
```

**Comment by WuglyakBolgoink** [comment]
@raphinesse 

What I have:

- cordova - v10.0.0
- node - 14.15.5
- npm - 6.14.11

----

1. create cordova project

```bash
cordova create test157 com.example.test157 test157
```

2. open folder

```bash
cd test157
```

3. install ios platform

```bash
cordova platform add ios@6.2.0
```

4. Do prepare -> this should be OK

```bash
cordova prepare --verbose --debug
```

5. Add this two commented edit-config's into ios section
```xml

<!--        <edit-config file="*-Info.plist" mode="merge" target="NSContactsUsageDescription">-->
<!--            <string>NSContactsUsageDescription test</string>-->
<!--        </edit-config>-->


<!--        <edit-config file="*-Info.plist" mode="merge" target="NSPhotoLibraryUsageDescription">-->
<!--            <string>NSPhotoLibraryUsageDescription test</string>-->
<!--        </edit-config>-->
```

6. Do prepare -> this should be OK

```bash
cordova prepare --verbose --debug
```

7. Uncomment first config

```xml
        <edit-config file="*-Info.plist" mode="merge" target="NSContactsUsageDescription">
            <string>NSContactsUsageDescription test</string>
        </edit-config>
```

8. Do prepare -> this should be OK

```bash
cordova prepare --verbose --debug
```

9. Uncomment second config

```xml
        <edit-config file="*-Info.plist" mode="merge" target="NSPhotoLibraryUsageDescription">
            <string>NSPhotoLibraryUsageDescription test</string>
        </edit-config>
```

10. this should throw an error

```bash
cordova prepare --verbose --debug
```


```
Prepared iOS project successfully
doc.find is not a function
TypeError: doc.find is not a function
    at Object.resolveParent (/Users/xxxUSERxxx/.npm-global/lib/node_modules/cordova/node_modules/cordova-common/src/util/xml-helpers.js:132:24)
    at /Users/xxxUSERxxx/.npm-global/lib/node_modules/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:315:59
    at Array.forEach (<anonymous>)
    at PlatformMunger._is_conflicting (/Users/xxxUSERxxx/.npm-global/lib/node_modules/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:307:21)
    at PlatformMunger.add_config_changes (/Users/xxxUSERxxx/.npm-global/lib/node_modules/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:176:44)
    at /Users/xxxUSERxxx/.npm-global/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare/platforms.js:66:24
    at async Promise.all (index 0)
```

**Comment by raphinesse** [comment]
Thanks for the quick response. I'll try to take a look at this soon.

**Comment by raphinesse** [comment]
I can confirm the error occurs on my machine too.

**Comment by raphinesse** [comment]
I just created a PR to fix this issue. It would be great if you could test if it resolves your problem.

**Comment by WuglyakBolgoink** [comment]
Thank you @raphinesse !

I will check it on this week
