### ISSUE TITLE
FileUpdater fails to copy symlinked files

### ISSUE THREAD

**Issue by breautek** [apache/cordova-common#91]
# Bug Report

## Problem
`cordova prepare` errors out when it has to copy files that are symlinks.

### What is expected to happen?
Not not error out and copy files successfully.

### What does actually happen?
Produces stacktrace, as shown below.

## Information

```
copy  www/node_modules/@totalpave/cordova-plugin-date/node_modules/.bin/atob platforms/ios/www/node_modules/@totalpave/cordova-plugin-date/node_modules/.bin/atob (updated file)
Cannot copy '../atob/bin/atob.js' to a subdirectory of itself, '../atob/bin/atob.js'.
Error: Cannot copy '../atob/bin/atob.js' to a subdirectory of itself, '../atob/bin/atob.js'.
    at onLink (/Users/normanbreau/development/tp-pci-client/node_modules/fs-extra/lib/copy-sync/copy-sync.js:146:13)
    at getStats (/Users/normanbreau/development/tp-pci-client/node_modules/fs-extra/lib/copy-sync/copy-sync.js:49:45)
    at startCopy (/Users/normanbreau/development/tp-pci-client/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/Users/normanbreau/development/tp-pci-client/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/Users/normanbreau/development/tp-pci-client/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at updatePathWithStats (/Users/normanbreau/development/tp-pci-client/node_modules/cordova-common/src/FileUpdater.js:103:24)
    at /Users/normanbreau/development/tp-pci-client/node_modules/cordova-common/src/FileUpdater.js:298:19
    at Array.forEach (<anonymous>)
    at Object.mergeAndUpdateDir (/Users/normanbreau/development/tp-pci-client/node_modules/cordova-common/src/FileUpdater.js:296:33)
    at updateWww (/Users/normanbreau/development/tp-pci-client/platforms/ios/cordova/lib/prepare.js:162:17)
```

The file `www/node_modules/@totalpave/cordova-plugin-date/node_modules/.bin/atob` is a symlink to `../atob/bin/atob.js`, which `fs-extra` seems to not handle properly without the `dereference` option enabled.

Also probably related to an issue reported in `cordova-android` platform:
https://github.com/apache/cordova-android/issues/693

### Command or Code

```
cordova plugin add @totalpave/cordova-plugin-date
cordova prepare ios
```

### Environment, Platform, Device

Mac OS X Mojave

### Version information

Cordova 9

## Other useful information
Modifying the following line: https://github.com/apache/cordova-common/blob/cfa7b3e5f809bc046d109f0b1f98666058e46cd1/src/FileUpdater.js#L103

To include the `deference` option fixed the issue for me.
https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/copy-sync.md

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by brodybits** [comment]
Interesting. Do you have time to make a PR with proposed bugfix and test case?

**Comment by breautek** [comment]
Yah i can make a proper pr. My change was done locally directly inside node_modules for a quick test.

**Comment by breautek** [comment]
I haven't been able to reproduce it, this was originally produced on my workmates mac as he is the one working on cordova projects. 

But talking to erisu, I guess adding the `dereference` option was required in other places as well. So I'll still go ahead with making that PR later tonight. I'm not confident it will resolve https://github.com/apache/cordova-android/issues/693 though, since I don't know if the error was occurring on symlinks or not. The original reporter was running on windows, which I don't believe has a concept of symlinks.

**Comment by raphinesse** [comment]
Frankly, I would not approve a PR when we not really know if it would fix this issue. Just tacking `dereference` onto every file copy will break features such as linking plugins or node modules. I don't know if it would be an issue here, but it should be considered.



> The original reporter was running on windows, which I don't believe has a concept of symlinks.

Windows does have hardlinks, symlinks and junctions (like symlinks, but a bit more restricted).
